console.log("Hello! I'm your coding fun fact guide!");
let botName = "Dani";
let botLocation  = "Earth";
let favoriteLanguage   = "JavaScript";
console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is " + favoriteLanguage + ".");
let codingFact = favoriteLanguage;
console.log(codingFact);
codingFact = 'I love ' + favoriteLanguage;
console.log(codingFact);
codingFact = 'I love ' + favoriteLanguage + ", " + favoriteLanguage + " is the best!";
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");